version: '3'
networks:
  bridge:
    driver: bridge
services:  
  mysqldb:    
    image: mysql:5.7       
    container_name: mysqldb_my_izihelp   
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: izihelp246
      MYSQL_DATABASE: my_izihelp            
    volumes:
      - my-datavolume:/var/lib/mysql        
    networks:
      - bridge   
    ports:
      - 3307:3306        
  backend:
    depends_on:
      - mysqldb
    container_name: backend_my_izihelp  
    build: 
      context: ./stack-be
    ports:
      - 7000:8000    
    networks:
      - bridge   
    environment:        
      - DATABASE_PORT:3307   
      - HOST:host.docker.internal    
volumes:
  my-datavolume:
# docker compose -p my-izihelp up -d